"""Insert user relationship to analytics

Revision ID: c4f9d9998a83
Revises: 0c99ba3f641c
Create Date: 2026-01-20 17:39:12.485111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f9d9998a83'
down_revision: Union[str, Sequence[str], None] = '0c99ba3f641c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'analytics', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analytics', type_='foreignkey')
    op.drop_column('analytics', 'user_id')
    # ### end Alembic commands ###
