"""empty message

Revision ID: ce3a794316da
Revises: 6c325f3a0d5b
Create Date: 2026-01-18 21:21:31.683500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3a794316da'
down_revision: Union[str, Sequence[str], None] = '6c325f3a0d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('total_messages', sa.Integer(), nullable=False))
    op.add_column('analytics', sa.Column('user_messages', sa.Integer(), nullable=False))
    op.add_column('analytics', sa.Column('assistant_messages', sa.Integer(), nullable=False))
    op.add_column('analytics', sa.Column('avg_confidence', sa.Float(), nullable=True))
    op.add_column('analytics', sa.Column('avg_latency_ms', sa.Integer(), nullable=True))
    op.add_column('analytics', sa.Column('total_tokens', sa.Integer(), nullable=True))
    op.add_column('analytics', sa.Column('resolved', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'analytics', ['conversation_id'])
    op.drop_constraint(op.f('analytics_user_id_fkey'), 'analytics', type_='foreignkey')
    op.drop_column('analytics', 'answer')
    op.drop_column('analytics', 'question')
    op.drop_column('analytics', 'user_id')
    op.drop_column('analytics', 'confidence')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('analytics', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('analytics', sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('analytics', sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('analytics_user_id_fkey'), 'analytics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'analytics', type_='unique')
    op.drop_column('analytics', 'resolved')
    op.drop_column('analytics', 'total_tokens')
    op.drop_column('analytics', 'avg_latency_ms')
    op.drop_column('analytics', 'avg_confidence')
    op.drop_column('analytics', 'assistant_messages')
    op.drop_column('analytics', 'user_messages')
    op.drop_column('analytics', 'total_messages')
    # ### end Alembic commands ###
